CREATE TABLE exercises (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    exercisename TEXT NOT NULL,
    sets TEXT,
    repetitions TEXT,
    weight INTEGER NOT NULL,
    time TEXT,
    calories INTEGER NOT NULL,
    workoutId INTEGER REFERENCES workouts(id) 
);